services:
  db:
    image: postgres:16-alpine
    container_name: packs_service_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: packs
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./internal/platform/dataprovider/database:/schema:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d packs"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}


